version: '3'

services:
  database:
    platform: linux/x86_64
    image: mysql
    ports:
      - "3306:3306"
    container_name: vinylish_db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=vinylish
  adminer:
    image: adminer
    ports:
      - "9090:8080"
  api:
    image: docker.oryfox.de/vinylapi
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://vinylish_db:3306/vinylish
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_HIBERNATE_DDL-AUTO=update