name: Deploy Frontend
on:
  push:
    branches:
      - master
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.3.0
      with:
        node-version: 16.15.1
    
    - name: Go into frontend
      run: cd frontend
      
    - name: Npm install
      working-directory: ./frontend
      run: npm i
    
    - name: Npm Build
      working-directory: ./frontend
      run: npm run build
      
    - name: Create Identity File
      working-directory: ./frontend
      run: echo "${{ secrets.SSH_KEY }}" >> i.key && chmod 400 i.key
      
    - name: Add remote key
      run: mkdir -p ~/.ssh/ && ssh-keyscan -t rsa vinyl.oryfox.de >> ~/.ssh/known_hosts
    
    - name: SCP Files
      working-directory: ./frontend
      run: scp -i i.key -r dist/* actions@vinyl.oryfox.de:/var/www/vinyl
