name: Push Docker Image

on:
  push:
    branches:
    - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.oryfox.de/vinylapi
      
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        registry: docker.oryfox.de
        username: ${{ secrets.DOCKER_REGISTRY_USER }}
        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: vinylapi:latest
