name: Push Docker Image

on:
  push:
    branches:
    - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker registry
      uses: docker/login-action@v1
      with:
        registry: docker.oryfox.de
        username: ${{ secrets.DOCKER_REGISTRY_USER }}
        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      
    - name: Build image and push Docker registry
      uses: docker/build-push-action@v2
      with:
        context: ./
        tags: |
          docker.oryfox.de/vinylapi:latest 
        push: true
