name: Push Docker Image

on:
  push:
    branches:
    - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Docker Registry
      run: docker login docker.oryfox.de --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_REGISTRY_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      
    - name: Build image and push Docker registry
      uses: docker/build-push-action@v2
      with:
        context: ./
        tags: |
          docker.oryfox.de/vinylapi:latest 
        push: true
